language: scala
jdk:
  - openjdk7
scala:
  - 2.10.3
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - fwbrasil@gmail.com
services:
  - mongodb
env:
  - travis=true category=memory
  - travis=true category=prevalent
  - travis=true category=mongo
  - travis=true category=relational
  - travis=true category=relational_mem
  - travis=true category=polyglot
before_script:
  - mysql -e 'create database activate_test;'
  - mysql -e 'create database activate_test_async;'
  - mysql -e 'create database activate_test_polyglot;'
  - mysql -e 'create database activate_test_polyglot_async;'
  - psql -c 'create database activate_test;' -U postgres
  - psql -c 'create database activate_test_async;' -U postgres
  - psql -c 'create database activate_test_polyglot;' -U postgres
  - psql -c 'create database activate_test_polyglot_async;' -U postgres
  - sleep 10
  - mongo mydb_test --eval 'db.addUser("activate_test", "activate_test");'