# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.9.1
# whitelist branches for now.  need backport branch to support 2.8.x
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - fwbrasil@gmail.com
env:
  - DB=memoryStorage
  - DB=prevaylerStorage
  - DB=mongoStorage
  - DB=postgresStorage
  - DB=mysqlStorage
before_script:
  - mysql -e 'create database activate_test;'
  - psql -c 'create database activate_test;' -U postgres
  - mongo mydb_test --eval 'db.addUser("activate_test", "activate_test");'