language: scala
jdk:
  - openjdk7
scala:
  - 2.10.3
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - fwbrasil@gmail.com
services:
  - mongodb
env:
  - DB=memoryStorage
  - DB=prevaylerStorage
  - DB=mongoStorage
  - DB=postgresStorage
  - DB=mysqlStorage
before_script:
  - mysql -e 'create database activate_test;'
  - psql -c 'create database activate_test;' -U postgres
  - mongo mydb_test --eval 'db.addUser("activate_test", "activate_test");'